name: Fishing_plugin
version: '${version}'
main: com.github.majisyou.fishing_plugin.Fishing_plugin
api-version: 1.18
authors: [ majisyou ]
description: fishing_plugin

commands:
  fishing_config_reload:
    description: configをリロードするぜ
    usage: 原因不明の失敗
    permission: fisingPrince.op

  fishing_rod:
    description: cutom_fishが釣れる釣り竿を生成するよ
    usage: 原因不明の失敗
    permission: fisingPrince.rod

  fish_shop:
    description: shop
    usage: 原因不明の失敗
    permission: fisingPrince.shop

  summon_fisherman:
    description: summon_fisherman
    usage: 原因不明の失敗
    permission: fisingPrince.op

  make_fish:
    description: make_fish
    usage: コマンドが失敗した
    permission: fisingPrince.op
